name: Build and Test

on: [push, pull_request]

env:
  DOTNET_VERSION: "3.1.100" # set this to the dot net version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@master

      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Build
      - name: dotnet build
        run: .\scripts\build.ps1
        shell: powershell

      # Build
      - name: dotnet test
        run: .\scripts\test.ps1
        shell: powershell
